### ISSUE TITLE
Assertion Fails

### ISSUE THREAD

**Issue by tovabaharlias** [cisc3130/1-vector#7]
I keep getting an assertion fail at line 63. I updated main.cpp since the changes
Assertion failed: (v1[i]==arr[i-1]), function main, line 63.
Abort trap: 6
I'm not sure how to fix this.
@rivlev

**Comment by rivlev** [comment]
This means that something is wrong with your insertion implementation.
The first assertion in this group checks that your vector has grown by one element. The second and third check that everything until pos is the same, and that the element at index pos is the inserted element. Passing all those means that all those things work.
The problem is after pos, the elements have not been shifted down correctly.
